CREATE TABLE clientes (
    active BOOLEAN,
    dt_register TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255),
    email VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE pedidos (
    price_total NUMERIC(38,2),
    client_id BIGINT,
    dt_order TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT,
    items VARCHAR(255),
    number_order VARCHAR(255),
    observations VARCHAR(255),
    status VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE produtos (
    available BOOLEAN,
    price NUMERIC(38,2),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT,
    category VARCHAR(255),
    description VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE restaurantes (
    active BOOLEAN,
    fee_delivery NUMERIC(38,2),
    feedback NUMERIC(38,2),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255),
    category VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255),
    PRIMARY_KEY (id)
);

ALTER TABLE IF EXISTS pedidos
   ADD CONSTRAINT FKqevrhgdyl1osl69f4dj8ubr2e
   FOREIGN KEY (restaurant_id)
   REFERENCES restaurantes;